### ISSUE TITLE
How to automatically load?

### ISSUE THREAD

**Issue by leabdalla** [teepluss/laravel-faker#2]
I've tried this in the **start.php**, but no success:

``` php
Event::listen('laravel.started: application', function(){
    $faker = Faker::make('en_US');
});
```

Then in my view:

``` php
<?=$faker->name?>
```

**Comment by teepluss** [comment]
$faker = Faker::make(
View::share('faker', $faker)

**Comment by leabdalla** [comment]
Class 'Faker' not found

**Comment by teepluss** [comment]
Event::listen('laravel.started: application', function() use (Faker) {
$faker = Faker::make('en_US');
});  

## 

Tee++
Email: teepluss@gmail.com
